// templateiso.js
// Здесь можно добавлять или редактировать шаблоны Гео
// Пример строки: "Тест": ["RU", "BY", "KZ", "UA", "AM", "GE"],
const geoTemplates = {
    "WW": ["ID","IN","US","EG","BR","PH","MX","JP","MY","FR","VN","PK","BD","IT","GB","CA","DE","ZA","AR","ES","NG","MA","DZ","TW","PE","SA","CO","CL","AE","TH","NP","SG","AU","EC","LK","VE","KR","TR","IQ","RO","HK","BO","PL","RS","RU","CN","BE","KE","SE","TN","JO","PT","QA","KW","UA","OM","HR","GT","DO","CH","KZ","GR","TZ","PA","AT","KH","GH","NZ","BG","HN","JM","HU","ZM","LY","IE","BA","SV","CR","UZ","BH","TT","CI","PY","NO","MM","CD","FI","ET","SY","DK","MR","SK","UG","PS","UY","LB","NL","AL","SN","NI","AO","MK","IR","BN","ZW","CM","MN","CZ","MU","SI","XK","KG","BY","LV","PR","LT","YE","AZ","SD","SO","MW","MV","GA","GY","RW","MG","BF","LA","ME","PG","SR","BW","MD","MT","ML","CU","IL","MO","BB","MZ","BS","TG","RE","NA","FJ","BZ","BJ","GE","LU","HT","AF","CG","AM","SZ","GP","IS","CY","GD","BT","EE","LC","TJ","TL","LS","MQ","GM","GN","GU","CW","SB","SC","SL","PF","VC","GF","LR","AG","KY","NE","CV","DM","NC","AW","TM","SX","KN","SS","AS","VU","TD","DJ","BM","MP","VG","VI","BI","WS","TC","JE","AD","TO","YT","GQ","PW","FM","IM","GI","BQ","MH","KI","MC","KM","AI","GW","CK","FO","GG","ST","MF","SM","AX","CF","LI","TV","MS","NR","GL","IO","ER","SH","FK","PM","BL","WF","NF","NU","KP","VA"],
  "WW-1/2": ["ID","US","BR","MX","MY","VN","BD","GB","DE","AR","NG","DZ","PE","CO","AE","NP","AU","LK","KR","IQ","HK","PL","RU","BE","SE","JO","QA","UA","HR","DO","KZ","TZ","AT","GH","BG","JM","ZM","IE","SV","UZ","TT","PY","MM","FI","SY","MR","UG","UY","NL","SN","AO","IR","ZW","MN","MU","XK","BY","PR","YE","SD","MW","GA","RW","BF","ME","SR","MD","ML","IL","BB","BS","RE","FJ","BJ","LU","AF","AM","GP","CY","BT","LC","TL","MQ","GN","CW","SC","PF","GF","AG","NE","DM","AW","SX","SS","VU","DJ","MP","VI","WS","JE","TO","GQ","FM","GI","MH","MC","AI","CK","GG","MF","AX","LI","MS","GL","ER","FK","BL","NF","KP"],
  "WW-2/2": ["IN","EG","PH","JP","FR","PK","IT","CA","ZA","ES","MA","TW","SA","CL","TH","SG","EC","VE","TR","RO","BO","RS","CN","KE","TN","PT","KW","OM","GT","CH","GR","PA","KH","NZ","HN","HU","LY","BA","CR","BH","CI","NO","CD","ET","DK","SK","PS","LB","AL","NI","MK","BN","CM","CZ","SI","KG","LV","LT","AZ","SO","MV","GY","MG","LA","PG","BW","MT","CU","MO","MZ","TG","NA","BZ","GE","HT","CG","SZ","IS","GD","EE","TJ","LS","GM","GU","SB","SL","VC","LR","KY","CV","NC","TM","KN","AS","TD","BM","VG","BI","TC","AD","YT","PW","IM","BQ","KI","KM","GW","FO","ST","SM","CF","TV","NR","IO","SH","PM","WF","NU","VA"],
  "WW-1/3": ["ID","EG","MX","FR","BD","CA","AR","MA","PE","CL","NP","EC","KR","RO","PL","CN","SE","PT","UA","GT","KZ","PA","GH","HN","ZM","BA","UZ","CI","MM","ET","MR","PS","NL","NI","IR","CM","MU","KG","PR","AZ","MW","GY","BF","PG","MD","CU","BB","TG","FJ","GE","AF","SZ","CY","EE","TL","GM","CW","SL","GF","KY","DM","TM","SS","TD","MP","BI","JE","YT","FM","BQ","MC","GW","GG","SM","LI","NR","ER","PM","NF","VA"],
  "WW-2/3": ["IN","BR","JP","VN","IT","DE","ES","DZ","SA","AE","SG","LK","TR","HK","RS","BE","TN","QA","OM","DO","GR","AT","NZ","JM","LY","SV","BH","PY","CD","SY","SK","UY","AL","AO","BN","MN","SI","BY","LT","SD","MV","RW","LA","SR","MT","IL","MZ","RE","BZ","LU","CG","GP","GD","LC","LS","GN","SB","PF","LR","NE","NC","SX","AS","DJ","VG","WS","AD","GQ","IM","MH","KM","CK","ST","AX","TV","GL","SH","BL","NU"],
  "WW-3/3": ["US","PH","MY","PK","GB","ZA","NG","TW","CO","TH","AU","VE","IQ","BO","RU","KE","JO","KW","HR","CH","TZ","KH","BG","HU","IE","CR","TT","NO","FI","DK","UG","LB","SN","MK","ZW","CZ","XK","LV","YE","SO","GA","MG","ME","BW","ML","MO","BS","NA","BJ","HT","AM","IS","BT","TJ","MQ","GU","SC","VC","AG","CV","AW","KN","VU","BM","VI","TC","TO","PW","GI","KI","AI","FO","MF","CF","MS","IO","FK","WF","KP"],
  "Tier I": ["AU","AT","BE","CA","FI","FR","DE","NL","NZ","NO","ZA","SE","CH","UK","US"],
  "Tier II": ["AO","BY","BR","BG","CM","CL","CN","CD","HR","CY","CZ","DK","EC","EE","HN","HU","CI","JP","KZ","KE","LV","LT","ML","MZ","NG","PA","PE","RO","RU","SN","RS","KR","ES","TH","UG","UA"],
  "Tier III": ["AX","AF","AL","DZ","AS","AD","AI","AQ","AG","AR","AM","AW","AZ","BS","BH","BD","BB","BZ","BJ","BM","BT","BO","BA","BW","IO","BN","BF","BI","KH","IC","CV","BQ","KY","CF","TD","CX","CC","CO","KM","CG","CK","CR","CU","CW","DJ","DM","DO","TL","EG","SV","GQ","ER","SZ","ET","FK","FO","FJ","GF","PF","TF","GA","GE","GH","GI","GR","GL","GD","GP","GU","GT","GG","GN","GW","GY","HT","HK","IS","IN","ID","IR","IQ","IE","IM","IL","IT","JM","JE","JO","KI","XK","KW","KG","LA","LB","LS","LR","LY","LI","LU","MO","MG","MW","MY","MV","MT","MH","MQ","MR","MU","YT","MX","FM","MD","MC","MN","ME","MS","MA","MM","NA","NR","NP","NC","NI","NE","NU","NF","KP","MK","MP","OM","PK","PW","PS","PG","PY","PH","PN","PL","PT","PR","QA","RE","RW","BL","SH","KN","LC","MF","PM","VC","WS","SM","ST","SA","SC","SL","SG","SX","SK","SI","SB","SO","GS","SS","LK","SD","SR","SJ","SY","TW","TJ","TZ","GM","TG","TK","TO","TT","TN","TR","TM","TC","TV","AE","UM","UY","UZ","VU","VA","VE","VN","VG","VI","WF","EH","YE","ZM","ZW"],
  "UTC+(0-2)": ["BF","CI","GH","GM","GN","GW","IS","LR","ML","MR","SH","SL","SN","ST","TG","AO","BJ","CD","CF","CG","CM","DZ","FO","GA","GB","GG","GQ","IE","IM","JE","MA","NE","NG","PT","TD","TN","EH","AD","AL","AT","BA","BE","BI","BW","CH","CZ","DE","DK","ES","FR","GI","HR","HU","IT","LI","LS","LU","LY","MC","ME","MK","MT","MW","MZ","NA","NL","NO","PL","RS","RW","SD","SE","SI","SJ","SK","SM","SS","SZ","VA","XK","ZA","ZM","ZW"],
  "UTC+(3-5)": ["AX","BG","BH","CY","DJ","EE","EG","ER","ET","FI","GR","IL","IQ","IR","JO","KE","KM","KW","LB","LT","LV","MD","MG","PS","QA","RO","SA","SO","SY","TR","TZ","UG","YE","YT","UA","BY","RU","AE","AF","AM","AZ","GE","MU","OM","RE","SC","IN","KZ","LK","MV","PK","TJ","TM","UZ"],
  "UTC+(6-8)": ["BD","BT","IO","KG","MM","NP","ID","KH","LA","TH","VN","BN","CN","HK","MN","MO","MY","PH","SG","TW"],
  "UTC+(9-11)": ["JP","KR","PW","TL","KP","AU","GU","MP","PG","FM","NC","SB","VU","NF"],
  "UTC+(12-14)": ["FJ","MH","NR","NZ","TV","WF","AQ","AS","TO","WS","TK","CK","KI","PF"],
  "UTC-(4-6)": ["BZ","CR","GT","HN","NI","SV","CO","EC","JM","KY","MX","PA","PE","AG","AI","AW","BB","BL","BM","BO","BQ","BS","CA","CL","CU","CW","DM","DO","GD","GP","GY","HT","KN","LC","MF","MQ","MS","PR","PY","SX","TC","TT","US","VC","VE","VG","VI"],
  "UTC-(1-3)": ["AR","BR","FK","GF","SR","UY","GL","PM","CV"],
  };


